### ISSUE TITLE
rethinkdb-cloud addon on heroku

### ISSUE THREAD

**Issue by nishantmodak** [rethinkdb/rails-nobrainer-blog#3]
The `rethinkdb-cloud` addon on heroku is no longer available.

Any other addon to try this out?

**Comment by nelsonic** [comment]
Any progress on having a RethinkDB Heroku Addon?

**Comment by danielmewes** [comment]
@nelsonic Sorry, haven't gotten to it yet.
If you want to pair Heroku with a RethinkDB database hosted by Compose in the meantime, you might be interested in these posts: https://www.compose.io/articles/tunneling-from-heroku-to-compose-rethinkdb/ ,  http://blog.fanout.io/2015/05/20/building-a-realtime-api-with-rethinkdb/

**Comment by aleclarson** [comment]
Any news on a RethinkDB Heroku Addon?

**Comment by sylvainlap** [comment]
+1

**Comment by danielmewes** [comment]
No news on this yet. We've been very busy working on new features, improvements and other integrations for the past year. Unfortunately we've not gotten around to looking into Heroku integration from our end yet.

**Comment by GeoffreyPlitt** [comment]
+1

**Comment by nelsonic** [comment]
Heroku integration would be a game-changer.

**Comment by tayler-king** [comment]
I'm also looking into this. I'm more than likely going to work on it myself, seeming as though nobody else is interested in the task.

**Comment by GeoffreyPlitt** [comment]
Cool - I'll help you test it
